
<link href="templatemo_style.css" rel="stylesheet" type="text/css" />
<style type="text/css">
.style6 {
	font-family: "Comic Sans MS";
	font-size: 14px;
}
</style>
<p align="justify"><img src="img/b.jpg" width="400" height="200" align="absbottom" /></p>
<p align="justify"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="style6">Bank pembangunan daerah  sumatera barat secara resmi berdiri pada tanggal 12 maret 1962 dengan nama PT.  BANK PEMBANGUNAN DAERAH SUMATERA BARAT yang disahkan melalui akta notaris Hasan  Qalbi di padang. Pendirian tersebut dipelopor oleh pemerintah daerah beserta  tokoh masyarakat dan tokoh pengusaha swasta disumatera barat atas dasar  pemikiran perlunya suatu lembaga keuangan yang berbentuk bank, yang secara  khusus membantu pemerintah dalam melaksanakan pembangunan daerah. Disahkan  melalui surat keputusan wakil menteri pertama bidang keuangan republik  Indonesia No. BUM 9-44/11 tentang izin usaha PT. Bank Pembangunan Daerah  Sumatera Barat, dan dimulailah operasional PT. Bank Pembangunan Daerah Sumatera  Barat dengan kedudukan di padang. <br />
  Dengan&nbsp;  keluarnya&nbsp;&nbsp; Undang-Undang&nbsp;&nbsp; No.&nbsp;&nbsp;  13&nbsp;&nbsp; Tahun&nbsp;&nbsp; 1962&nbsp;&nbsp;  tanggal&nbsp;&nbsp; 16&nbsp;&nbsp; Agustus 1962&nbsp;&nbsp; yaitu&nbsp;&nbsp;  tentang&nbsp;&nbsp; Ketentuan-Ketentuan Pokok  Bank Pembangunan Daerah, maka dasar hukum pendirian Bank Pembangunan Daerah  harus diganti yaitu dengan Peraturan Daerah tingkat I propinsi Sumatera Barat  No. 4 sehingga PT. Bank Pembangunan Daerah Sumatera Barat diubah menjadi Bank  Pembangunan Daerah Sumatera Barat. Dalam perjalanan nya tahun 1996 disahkan  penyebutan nama sebagai &ldquo;Bank Nagari&rdquo; dengan maksud untuk lebih dikenal,  membangun <em>brand image</em> sekaligus  mengimpresikan tatanan sistem pemerintah di Sumatera Barat.</span></p>
<div align="justify" class="style6">Sesuai dengan perkembangan dan lebih leluasa  dalam menjalankan bisnis, tanggal 16 Agustus 2006 berdasarkan peraturan daerah  Propinsi Sumatera Barat No. 3 Tahun 2006, bentuk badan hukum Bank Pembangunan  Daerah Sumatera Barat berubah menjadi perusahaan daerah menjadi perseroan  terbatas. Yang didirikan berdasarkan akta pendirian perseroan Nomor 1 Tanggal 1  Februari 2007 dihadapan&nbsp; Notaris H.Hendri  Hinal, S.H, Dan disahkan oleh Menteri Hukum dan Hak Azazi Manusia Republik  Indonesia dengan keputusan Nomor W3-00074 HT .01.01.TH.2007 tanggal 4 April  2007. Saat ini Bank Nagari telah berstatus sebagai Bank Devisa serta telah  memiliki unit Usaha Syariah. Bank Nagari juga merupakan Bank Pembangunan Daerah  pertama yang membuka Kantor Cabang diluar Daerah.</div>
